name: FirstCIWorkflow

on:
  push: 
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  # The next is the name of the job (build)
  build: 
    # The next sets the runner of the job
    runs-on: ubuntu-latest

    # Indicates which Python image to use
    # must match the version used to develop
    # in this project of course
    container: python:3.9-slim

    steps:
        - name: Checkout
          uses: actions/checkout@v3

        # In this step we use pipi (|) to execute
        # two shell commands in one step 
        - name: Install dependencies
          run: |
            python -m pip install --upgrade pip 
            pip install -r requirements.txt

        - name: Lint with flake8
          run: | 
            flake8 service --count --select=E9,F63,F7,F82 --show-source --statistics
            flake8 service --count --max-complexity=10 --max-line-length=127 --statistics

        - name: Red unit tests with nose
          run: nosetests -v --with-spec --spec-color --with-coverage --cover-package=app